### ISSUE TITLE
saving draft strange recipient

### ISSUE THREAD

**Issue by lenny76** [umanamente/n8n-nodes-imap#41]
If I set the recipient when saving a draft email like maio@pippo.com
the email recipient is saved like this

maio@pippo.com <=?UTF-8?B?bWFpb0BwaXBwby5jb20=?=>

what's wrong?

thanks

**Comment by lenny76** [comment]
using RFC format works ok

From: sender@example.com
To: recipient@example.com
Subject: Test Email
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"

Questo è il corpo del messaggio.

**Comment by lenny76** [comment]
![Image](https://github.com/user-attachments/assets/ccd135b4-d82a-49ad-aedd-ee4171f33da5)

**Comment by umanamente** [comment]
Please install the beta version `n8n-nodes-imap@2.4.2-1-gbb54fc1-beta` and let me know if the issue is resolved.

**Comment by dabari** [comment]
@umanamente thanks for your work on the extension!

Unfortunately, it doesn't work with current release...

I just looked into your code, and it seems that you are not correctly handling RFC822 / RFC2047 encoding for "Input Format = Fields" option in the UI.

For example, in your code, you encode everything the user enters in the "To" field. According to the specification, this is incorrect – only the "display name" should be encoded. The actual email address, which contains only ASCII characters, must not be encoded.

https://github.com/umanamente/n8n-nodes-imap/blob/d94c91c49b4e4c870616a1ba68bc92953ed19afd/nodes/Imap/operations/email/functions/EmailCreateDraft.ts#L149


Unfortunately, I don't have time right now to set up the environment on my end, make the changes, test them, and create a PR. But I hope my explanation is clear, and that you can fix it much more quickly on your side.


----

## incorrect

```txt
From: sender@example.com
To: =?UTF-8?B?cmVjaXBpZW50QGV4YW1wbGUuY29t?=
Subject: Test Email
Content-Type: text/plain; charset="UTF-8"
```

gives

![Image](https://github.com/user-attachments/assets/097ccbd6-76c0-4faa-995a-68bb7ebbb635)

----

## correct

```txt
From: sender@example.com
To: =?UTF-8?B?RGlzcGxheSBOYW1l?= recipient@example.com
Subject: Test Email
Content-Type: text/plain; charset="UTF-8"
```

![Image](https://github.com/user-attachments/assets/0157354f-265a-4937-b44e-d99771ef9740)

gives

![Image](https://github.com/user-attachments/assets/67ffb2f3-792f-45e9-a39e-2fb00827e06c)


## or (only for ASCII e-mail address, without a visible name)

```txt
From: sender@example.com
To: sender@example.com
Subject: Test Email
Content-Type: text/plain; charset="UTF-8"
```

![Image](https://github.com/user-attachments/assets/4bc9a5ff-d7fc-4d7d-bfe7-9190649d271b)

----

thanks and greetings
Darijo

**Comment by umanamente** [comment]
@dabari Thanks for your analysis, this is valuable information for me. Yes, indeed, I implemented this in a rush since I didn't have a library on hand to convert to RFC 822. Now that these issues have come up, I found a library and replaced the implementation in the beta version. In the message above, I asked for it to be checked, but that didn’t happen.

Now I've released these changes in version 2.4.3.  
Please update the node and check if the issue is resolved.

**Comment by dabari** [comment]
> [@dabari](https://github.com/dabari) Thanks for your analysis, this is valuable information for me. Yes, indeed, I implemented this in a rush since I didn't have a library on hand to convert to RFC 822. Now that these issues have come up, I found a library and replaced the implementation in the beta version. In the message above, I asked for it to be checked, but that didn’t happen.
> 
> Now I've released these changes in version 2.4.3. Please update the node and check if the issue is resolved.

@umanamente no, unfortunately, the issue is still not fixed...

![Image](https://github.com/user-attachments/assets/a32369e1-ad30-4bbf-b117-3d0efbdf1182)

![Image](https://github.com/user-attachments/assets/262dfaa5-b2b4-4e2b-aa40-d5a755091c88)

![Image](https://github.com/user-attachments/assets/7ea45fe7-7383-44a2-8f63-79f60747dd07)

-----

Could you please check/debug the result of the string variable in your code using the same input as in my screenshot? (see marker 1 in the picture):

![Image](https://github.com/user-attachments/assets/e761a7a7-cf53-4e11-8d07-7b3de4ac7039)

Is it encoded correctly according to RFC822/RFC2047?

----
And... you're setting the email values in the object structure simply as an email string. 

![Image](https://github.com/user-attachments/assets/3e89095e-123f-415a-bd22-f7b67c76b67c)

According to nodemailer, this seems to work, **but** all examples in the nodemailer repo use the format `"Display Name email@address.com"`. 

![Image](https://github.com/user-attachments/assets/339e0727-fe87-4f4a-95dd-f03ee0336eb3)


Perhaps there's an issue at nodemailer if we using just the plain email string (the way you're doing it).

It might be better to explicitly store the fields in a separate JSON object, as described here: https://nodemailer.com/extras/mailcomposer/#address-formatting

e.g.

```js

let json_data = {
      from: from,
      to: { name: '', address: 'recipient@example.com' },
      subject: subject,
     text: text,
  };
```

**Comment by umanamente** [comment]
I created a `n8n-nodes-eml` node as a middleman to generate EML content. Could you please install and test the output?

Repo: https://github.com/umanamente/n8n-nodes-eml

**Comment by dabari** [comment]
Okay, I tested it with the EML-Compose node (see my workflow image), and the result is correct.
I also checked it with German special characters in the display name.

![Image](https://github.com/user-attachments/assets/5733859f-22cf-4100-83bb-beebec370df0)

For me, working with an EML node beforehand is a good and generic solution.

However, I think you should now decide in which node (EML or IMAP) you want to allow the "Fields" input. If both support it, it could be confusing for most users.

I would appreciate a short update on how you plan to handle this for "production" use.

Thanks for your quick and agile implementation!

**Comment by umanamente** [comment]
`n8n-nodes-eml` will be the main option for generating email drafts. Fields in the IMAP node will be deprecated, but I will keep the "fields" option for backward compatibility with a deprecation warning.
